import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import { FloatingMenu } from "@/components/menu/FloatingMenu";
import { FollowingMenu } from "@/components/menu/FollowingMenu";
import { FollowingProvider } from "@/context/FollowingContext";
import { LikeProvider } from "@/context/LikeContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<FollowingProvider>
			<LikeProvider>
				<html lang="en">
					<body>
						<Navbar />
						{children}
						<FloatingMenu />
						<FollowingMenu />
					</body>
				</html>
			</LikeProvider>
		</FollowingProvider>
	);
}
